/* Word Goblin — js/config.js
 * Optional deployment defaults. Everything here is PUBLIC (this file ships with the
 * app). encryptedScriptUrl is your backend address encrypted with your passphrase
 * (PBKDF2-SHA256 x 1,500,000 + AES-256-GCM) - safe to publish; the landing page
 * asks for the passphrase once per device. Generated by tools/encrypt-url.html.
 */
window.WORDGOBLIN_DEFAULTS = {
  scriptUrl: '',
  encryptedScriptUrl: {"v":1,"it":1500000,"salt":"imO7SCiWPQZ9feO4LK7tbA==","iv":"ORx64gRakSFR3hvS","ct":"Bls4JWBYqO6bIvfMW3sfc8xrMni0EmY23hvCbohxI8G4mJLTiFsl642w33XhW8iPAu/3/twlU9oFn88QYtjbkGVg75hYPF8kSlh/p7lD2j4GMMP5o0QEDxhfp21+zg1PpsDAVnOmnhMzn3SVHz0GsmAvC/3WvXkQ3Gt/PU7k/CNw0w=="}
};
